---
#- name: "Import test configuration tasks."
#  include_tasks: "templateTestConfiguration.yml"
#  tags:
#    - aspects_apache24
#    - aspects_apache24_configuration
#    - aspects_apache24_config

- name: "Include prod configuration tasks."
  include_tasks: "templateProdConfiguration.yml"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config
