---
- name: "install apache packages"
  include_tasks: "{{ ansible_pkg_mgr}}InstallPackages.yml"
  tags:
    - aspects_apache24
    - aspects_apache24_package_install

- name: "remove apache packages"
  include_tasks: "{{ ansible_pkg_mgr}}RemovePackages.yml"
  tags:
    - aspects_apache24
    - aspects_apache24_package_remove

- name: "Import configuration tasks."
  import_tasks: "configure.yml"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "Include selinuxSettings tasks"
  when: (ansible_selinux is defined and ansible_selinux != False) and
    ansible_selinux.status == "enabled" and
    aspects_apache24_selinux_change != False
  import_tasks: "selinuxSettings.yml"
  tags:
  - aspects_apache24
  - aspects_apache24_httpdconf
