---
# tasks file for aspects_apache24

- include: installPackages.yml
  tags:
  - aspects_apache24

- include: DebianMain.yml
  when:
    (ansible_distribution == "Ubuntu" and
    ansible_lsb.release == "14.04") or
    ansible_distribution == "Linuxmint"
  tags:
  - aspects_apache24
#
#- include: RedHatMain.yml
#  when:
#    (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7")
#  tags:
#  - aspects_apache24