---
# only init when aspects_apache24_enabled == true.
- include_tasks: "init.yml"
  when: aspects_apache24_enabled
        and not aspects_apache24_httpdconf is defined
  tags:
  - aspects_apache24
  - aspects_apache24_configuration
  - aspects_apache24_config
  - aspects_apache24_config_prod
  - aspects_apache24_config_test

- name: "Old Configuration Detected."
  when: aspects_apache24_httpdconf is defined
  debug:
    msg: "aspects_apache24_httpdconf is defined. All tasks have been skipped. Please update your configuration to use the new format."
  tags:
  - aspects_apache24