---
# Allow Apache to listen on tcp port ports listed in aspects_apache24_listen_ports
- name: RedHat - Open ports for httpd in SELinux settings.
  seport:
    state: present
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
  loop: "{{ aspects_apache24_listen_ports|default([]) }}"
  tags:
  - aspects_apache24
  - aspects_apache24_httpdconf

- name: RedHat - Allow httpd_can_network_connect in SELinux settings.
  when: aspects_apache24_selinux_httpd_can_network_connect
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  tags:
  - aspects_apache24
  - aspects_apache24_httpdconf
