---
- name: "ProdConfig - Create directories for apache configuration."
  file:
    state: "directory"
    dest: "{{ item }}"
    owner: "root"
    group: "root"
    mode: "0750"
  with_items: "{{ aspects_apache24_configuration_directories_list }}"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "ProdConfig - Symlink modules directory."
  file:
    state: "link"
    src: "{{ aspects_apache24_modules_root }}"
    dest: "{{ aspects_apache24_configuration_root }}/modules"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "ProdConfig - Symlink logs directory."
  file:
    state: "link"
    src: "{{ aspects_apache24_logs_root }}"
    dest: "{{ aspects_apache24_configuration_root }}/logs"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "ProdConfig - Template general configuration."
  when: item.value.enabled
  template:
    dest: "{{ aspects_apache24_configuration_root }}/aspects.conf.d/{{ item.value.weight }}-{{ item.value.name }}.conf"
    src: "general.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  with_dict: "{{ aspects_apache24_configuration_general }}"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "ProdConfig - Template module configuration."
  when: item.value.enabled
  template:
    dest: "{{ aspects_apache24_configuration_root }}/aspects.mods.d/{{ item.value.weight }}-{{ item.value.name }}.conf"
    src: "module.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  with_dict: "{{ aspects_apache24_configuration_modules }}"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "ProdConfig - Template VirtualHost configuration."
  when: item.value.enabled
  template:
    dest: "{{ aspects_apache24_configuration_root }}/aspects.vhosts.d/{{ item.value.weight }}-{{ item.value.name }}.conf"
    src: "vhost.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  with_dict: "{{ aspects_apache24_configuration_vhosts }}"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "ProdConfig - RedHat Family - Template main apache configuration file."
  when: ansible_os_family == 'RedHat'
  template:
    dest: "/etc/httpd/conf/httpd.conf"
    src: "main.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "ProdConfig - Debian Family - Template main apache configuration file."
  when: ansible_os_family == 'Debian'
  template:
    dest: "/etc/apache2/apache2.conf"
    src: "main.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config
