---
- name: "ProdConfig - Create directories for apache configuration."
  file:
    state: "directory"
    dest: "{{ item }}"
    owner: "root"
    group: "root"
    mode: "0750"
  loop: "{{ aspects_apache24_configuration_directories_list }}"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config
    - aspects_apache24_config_prod

- name: "ProdConfig - Symlink modules directory."
  file:
    state: "link"
    src: "{{ aspects_apache24_modules_root }}"
    dest: "{{ aspects_apache24_configuration_root }}/modules"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config
    - aspects_apache24_config_prod

- name: "ProdConfig - Symlink logs directory."
  file:
    state: "link"
    src: "{{ aspects_apache24_logs_root }}"
    dest: "{{ aspects_apache24_configuration_root }}/logs"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config
    - aspects_apache24_config_prod

- name: "ProdConfig - Template general configuration."
  when: item.1.enabled == True or item.1.enabled == "True"
  template:
    dest: "{{ aspects_apache24_configuration_root }}/aspects.conf.d/{{ item.1.weight }}-{{ item.1.name }}.conf"
    src: "general.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  loop: "{{ aspects_apache24_configuration_general | dictsort }}"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config
    - aspects_apache24_config_prod

- name: "ProdConfig - Remove disabled general configuration."
  when: item.1.enabled == False or item.1.enabled == "False"
  file:
    state: "absent"
    path: "{{ aspects_apache24_configuration_root }}/aspects.conf.d/{{ item.1.weight }}-{{ item.1.name }}.conf"
  loop: "{{ aspects_apache24_configuration_general | dictsort }}"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config
    - aspects_apache24_config_prod

- name: "ProdConfig - Template module configuration."
  when: item.1.enabled == True or item.1.enabled == "True"
  template:
    dest: "{{ aspects_apache24_configuration_root }}/aspects.mods.d/{{ item.1.weight }}-{{ item.1.name }}.conf"
    src: "module.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  loop: "{{ aspects_apache24_configuration_modules | dictsort }}"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config
    - aspects_apache24_config_prod

- name: "ProdConfig - Remove disabled module configuration."
  when: item.1.enabled == False or item.1.enabled == "False"
  file:
    state: "absent"
    path: "{{ aspects_apache24_configuration_root }}/aspects.mods.d/{{ item.1.weight }}-{{ item.1.name }}.conf"
  loop: "{{ aspects_apache24_configuration_modules | dictsort }}"
  notify: "Restart Apache"
  tags:
  - aspects_apache24
  - aspects_apache24_configuration
  - aspects_apache24_config
  - aspects_apache24_config_prod

- name: "ProdConfig - Template VirtualHost configuration."
  when: item.1.enabled == True or item.1.enabled == "True"
  template:
    dest: "{{ aspects_apache24_configuration_root }}/aspects.vhosts.d/{{ item.1.weight }}-{{ item.1.name }}.conf"
    src: "vhost.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  loop: "{{ aspects_apache24_configuration_vhosts | dictsort }}"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config
    - aspects_apache24_config_prod

- name: "ProdConfig - Remove disabled VirtualHost configuration."
  when: item.1.enabled == False or item.1.enabled == "False"
  file:
    state: "absent"
    path: "{{ aspects_apache24_configuration_root }}/aspects.vhosts.d/{{ item.1.weight }}-{{ item.1.name }}.conf"
  loop: "{{ aspects_apache24_configuration_vhosts | dictsort }}"
  notify: "Restart Apache"
  tags:
  - aspects_apache24
  - aspects_apache24_configuration
  - aspects_apache24_config
  - aspects_apache24_config_prod

- name: "ProdConfig - RedHat Family - Template main apache configuration file."
  when: ansible_os_family == 'RedHat'
  template:
    dest: "/etc/httpd/conf/httpd.conf"
    src: "main.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config
    - aspects_apache24_config_prod

- name: "ProdConfig - Debian Family - Template main apache configuration file."
  when: ansible_os_family == 'Debian'
  template:
    dest: "/etc/apache2/apache2.conf"
    src: "main.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  notify: "Restart Apache"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config
    - aspects_apache24_config_prod
