---
- name: "TestingConfig - Create directories for apache configuration."
  file:
    state: "directory"
    dest: "{{ item }}"
    owner: "root"
    group: "root"
    mode: "0750"
  with_items: "{{ aspects_apache24_test_configuration_directories_list }}"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "TestingConfig - Symlink modules directory."
  file:
    state: "link"
    src: "{{ aspects_apache24_modules_root }}"
    dest: "{{ aspects_apache24_test_configuration_root }}/modules"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "TestingConfig - Symlink logs directory."
  file:
    state: "link"
    src: "{{ aspects_apache24_logs_root }}"
    dest: "{{ aspects_apache24_test_configuration_root }}/logs"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config


- name: "TestingConfig - Template general configuration."
  when: item.value.enabled == "True"
  template:
    dest: "{{ aspects_apache24_test_configuration_root }}/aspects.conf.d/{{ item.value.weight }}-{{ item.value.name }}.conf"
    src: "general.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  with_dict: "{{ aspects_apache24_configuration_general }}"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "TestingConfig - Remove disabled general configuration."
  when: item.value.enabled == "False"
  file:
    state: "absent"
    path: "{{ aspects_apache24_test_configuration_root }}/aspects.conf.d/{{ item.value.weight }}-{{ item.value.name }}.conf"
  with_dict: "{{ aspects_apache24_configuration_general }}"
  tags:
  - aspects_apache24
  - aspects_apache24_configuration
  - aspects_apache24_config

- name: "TestingConfig - Template module configuration."
  when: item.value.enabled == "True"
  template:
    dest: "{{ aspects_apache24_test_configuration_root }}/aspects.mods.d/{{ item.value.weight }}-{{ item.value.name }}.conf"
    src: "module.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  with_dict: "{{ aspects_apache24_configuration_modules }}"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "TestingConfig - Remove disabled module configuration."
  when: item.value.enabled == "False"
  file:
    state: "absent"
    path: "{{ aspects_apache24_test_configuration_root }}/aspects.mods.d/{{ item.value.weight }}-{{ item.value.name }}.conf"
  with_dict: "{{ aspects_apache24_configuration_modules }}"
  tags:
  - aspects_apache24
  - aspects_apache24_configuration
  - aspects_apache24_config

- name: "TestingConfig - Template VirtualHost configuration."
  when: item.value.enabled == "True"
  template:
    dest: "{{ aspects_apache24_test_configuration_root }}/aspects.vhosts.d/{{ item.value.weight }}-{{ item.value.name }}.conf"
    src: "vhost.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
  with_dict: "{{ aspects_apache24_configuration_vhosts }}"
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "TestingConfig - Remove disabled VirtualHost configuration."
  when: item.value.enabled == "False"
  file:
    state: "absent"
    path: "{{ aspects_apache24_test_configuration_root }}/aspects.vhosts.d/{{ item.value.weight }}-{{ item.value.name }}.conf"
  with_dict: "{{ aspects_apache24_configuration_vhosts }}"
  tags:
  - aspects_apache24
  - aspects_apache24_configuration
  - aspects_apache24_config

- name: "TestingConfig - RedHat Family - Template main apache configuration file."
  when: ansible_os_family == 'RedHat'
  template:
    dest: "{{ aspects_apache24_test_configuration_root }}/httpd.conf"
    src: "main.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
    validate: 'httpd -t -f %s'
  register: inprocess_validation_result
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config

- name: "TestingConfig - Debian Family - Template main apache configuration file."
  when: ansible_os_family == 'Debian'
  template:
    dest: "{{ aspects_apache24_test_configuration_root }}/apache2.conf"
    src: "main.conf.j2"
    owner: "root"
    group: "root"
    mode: "0640"
    validate: 'apache2 -t -f %s'
  register: inprocess_validation_result
  tags:
    - aspects_apache24
    - aspects_apache24_configuration
    - aspects_apache24_config
