---
- name: yum - Remove packages on CentOS 7
  when:
    (
      item.value.CentOS is defined and
      item.value.CentOS.7 is defined and
      ansible_distribution == "CentOS" and
      ansible_distribution_major_version == "7" and
      item.value.state == "absent"
    )
  yum:
    name: "{{ item.value.CentOS.7 }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ aspects_apache24_packages }}"
  tags:
    - aspects_apache24
    - aspects_apache24_package_remove
    - aspects_apache24_package_remove_yum
