---

- name: "Restart Apache"
  service:
    name: "{% if ansible_os_family == 'RedHat' %}httpd{% elif ansible_os_family == 'Debian' %}apache2{% endif %}"
    state: restarted
    enabled: yes
  tags:
  - aspects_apache24

- name: "Reload Apache"
  service:
    name: "{% if ansible_os_family == 'RedHat' %}httpd{% elif ansible_os_family == 'Debian' %}apache2{% endif %}"
    state: reloaded
    enabled: yes
  tags:
  - aspects_apache24

- name: "Start Apache"
  service:
    name: "{% if ansible_os_family == 'RedHat' %}httpd{% elif ansible_os_family == 'Debian' %}apache2{% endif %}"
    state: started
    enabled: yes
  tags:
  - aspects_apache24

- name: "Stop Apache"
  service:
    name: "{% if ansible_os_family == 'RedHat' %}httpd{% elif ansible_os_family == 'Debian' %}apache2{% endif %}"
    state: stopped
    enabled: no
  tags:
  - aspects_apache24
