---
# file: roles/apache2/handlers/main.yml
- name: restart apache2
  service: name=apache2 state=restarted enabled=yes

- name: reload apache2
  service: name=apache2 state=reloaded enabled=yes

- name: start apache2
  service: name=apache2 state=started enabled=yes

- name: stop apache2
  service: name=apache2 state=stopped

- name: restart httpd
  service: name=httpd state=restarted enabled=yes

- name: reload httpd
  service: name=httpd state=reloaded enabled=yes

- name: start httpd
  service: name=httpd state=started enabled=yes

- name: stop httpd
  service: name=httpd state=stopped