---
# file: roles/apache2/handlers/main.yml
- name: restart apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
  tags:
  - aspects_apache24

- name: reload apache2
  service:
    name: apache2
    state: reloaded
    enabled: yes
  tags:
  - aspects_apache24

- name: start apache2
  service:
    name: apache2
    state: started
    enabled: yes
  tags:
  - aspects_apache24

- name: stop apache2
  service:
    name: apache2
    state: stopped
  tags:
  - aspects_apache24

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
  tags:
  - aspects_apache24

- name: reload httpd
  service:
    name: httpd
    state: reloaded
    enabled: yes
  tags:
  - aspects_apache24

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: yes
  tags:
  - aspects_apache24

- name: stop httpd
  service:
    name: httpd
    state: stopped
  tags:
  - aspects_apache24
